# Generated by Django 3.1 on 2020-08-27 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, validators=[django.core.validators.URLValidator()])),
                ('url_hash', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
